const SET_USER_ACTION = "SET_USER_ACTION"
const SET_SHOW_UNSUCCESSFUL_LOGIN_ALERT_ACTION = "SET_SHOW_UNSUCCESSFUL_LOGIN_ALERT_ACTION"
export { SET_USER_ACTION, SET_SHOW_UNSUCCESSFUL_LOGIN_ALERT_ACTION }