server:
  port: 8084
  servlet:
    context-path: /notification-service-api

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:9999/eureka/
#      enabled: false

spring:
  application:
    name: wayd-notification
  webflux:
    base-path: /notification-service-api
  datasource:
    url: jdbc:postgresql://localhost:5434/wayd_notification
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: ***
    password: ***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/auth/realms/WAYD/protocol/openid-connect/certs


wayd:
  kafka:
    address: localhost:9092
    groupId: notification
    producer:
      id: notification-producer
  jwt:
    secret: very-secret-key